version: '3.9'

services:
  db-auth:
    image: postgres:16.1-bullseye
    networks:
      - papper-backend
    volumes:
      - db_auth_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_CONTAINER_PORT}:${DB_PORT}'
  auth-service:
    build: auth-service
    container_name: auth-service
    networks:
      - papper-backend
    volumes:
      - ./auth-service:/usr/src/auth-service
    env_file:
      - .env
    ports:
      - ${HOST_PORT}:8000
    depends_on:
      - db-auth
    command: > 
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_auth_data:

networks:
  papper-backend:
    name: papper-backend
    external: true
